[package]
name = "simian_council"
version = "0.1.0"
authors = ["SlackMagiC <laurent.pietrzyk@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
serde = "*"
serde_json = "*"
serde_derive = "*"