[package]
name = "simian_council_bin"
version = "0.1.0"
authors = ["SlackMagiC <laurent.pietrzyk@gmail.com>"]
edition = "2018"

[dependencies]
ansi_term = "0.11.0"
simian_council= { path = "../simian-council" }